# Generated by Django 5.0 on 2024-10-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_first', models.FloatField()),
                ('num_second', models.FloatField()),
            ],
        ),
    ]
